---
services:
  weaviate:
    env_file:
      - ../.env
    command:
      - --host
      - 0.0.0.0
      - --port
      - "${WEAVIATE_INTERNAL_PORT:-8080}"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
      - "${WEAVIATE_HOST_PORT:-8080}:${WEAVIATE_INTERNAL_PORT:-8080}"
      - "${WEAVIATE_GRPC_PORT:-50051}:50051"
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-ollama"
      ENABLE_MODULES: "text2vec-ollama"
      CLUSTER_HOSTNAME: "node1"
    depends_on:
      ollama:
        condition: service_healthy
  ollama:
    env_file:
      - ../.env
    image: ollama/ollama
    volumes:
      - ./ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5

